### ISSUE TITLE
Help please, plugin seems don't work

### ISSUE THREAD

**Issue by copmir** [laymain/kafka-tool-avro#1]
Hi,
i tried to install plugin (copying into plugins folder) . When kafkatools2 restarts, in the "Content Types" topic drop-downs i choose "Avro" for key and message and click update.
when  i go in the data panel i find "Feature only available for licensed users" (i have a personal license)
I have seen in error.log too. there are this warnings....can you help me please?
Many thanks

09/apr/2019 12:52:57.371 WARN  com.kafkatool.common.ExternalDecoderManager - NoClassDefFoundError in tryLoading io.confluent.kafka.serializers.KafkaAvroEncoder, ex=kafka/serializer/Encoder
09/apr/2019 12:52:57.374 WARN  com.kafkatool.common.ExternalDecoderManager - NoClassDefFoundError in tryLoading io.confluent.kafka.serializers.KafkaAvroDecoder, ex=kafka/serializer/Decoder
09/apr/2019 12:52:57.376 WARN  com.kafkatool.common.ExternalDecoderManager - NoClassDefFoundError in tryLoading io.confluent.kafka.formatter.AvroMessageFormatter, ex=kafka/common/MessageFormatter
09/apr/2019 12:52:57.377 WARN  com.kafkatool.common.ExternalDecoderManager - NoClassDefFoundError in tryLoading io.confluent.kafka.formatter.AvroMessageReader, ex=kafka/common/MessageReader

**Comment by laymain** [comment]
Hi,

Message is quite self-explanatory: `Feature only available for licensed users`.
Kafka Tool does not allow the use of plugins for non licensed users.
There is no real personal license, only a free trial of 30 days.

> Kafka Tool can be evaluated for free for 30 days without any obligations, after the evaluation period you need to purchase a commercial license or uninstall the software if you are using the product for commercial, educational or non-profit purposes.
http://www.kafkatool.com/features.html

I'm sorry for that but it seems that you have to buy a license even if this plugin is provided free of charge

**Comment by copmir** [comment]
many thanks for the clarification

**Comment by laymain** [comment]
Just to be sure on these warnings, which version of Kafka Tool are you using?
