### ISSUE TITLE
Mac Kafka Tool plugins folder?

### ISSUE THREAD

**Issue by csingh** [laymain/kafka-tool-avro#13]
Hi, would love to use this plugin, but a potentially silly question...

Where would I drop this file on a Mac OS install of Kafka Tool?

Thanks!

**Comment by laymain** [comment]
Hi, have a look at this issue https://github.com/laymain/kafka-tool-avro/issues/6#issuecomment-575989470 ;)

**Comment by csingh** [comment]
Late reply but thank you! 😄
