### ISSUE TITLE
Can't set schema registry

### ISSUE THREAD

**Issue by gex1x** [laymain/kafka-tool-avro#15]
Hello!

From instruction:
Installation
Download the latest release of the plugin.
Copy the jar to the 'plugins' folder in the Kafka Tool installation folder.
Restart Kafka Tool.
Usage
Navigate to the topic that you want to use the decorator with.
In the "Content Types" drop-downs you should see the name "Avro".
Select it and click on "Update"

It' all done

But in error.log i see next:
15/фев/2021 13:03:37.170 INFO  com.kafkatool.common.ExternalDecoderManager - Finding plugins in directory C:\dev\bin\kafkatool2.0.7\plugins
15/фев/2021 13:03:37.170 INFO  com.kafkatool.common.ExternalDecoderManager - Found files in plugin directory, count=2
15/фев/2021 13:03:37.170 INFO  com.kafkatool.common.ExternalDecoderManager - Loading plugings from file C:\dev\bin\kafkatool2.0.7\plugins\kafka-tool-avro-1.0.4-jar-with-dependencies.jar
15/фев/2021 13:03:37.201 WARN  com.kafkatool.common.ExternalDecoderManager - NoClassDefFoundError in tryLoading io.confluent.kafka.formatter.AvroMessageReader, ex=kafka/common/MessageReader
15/фев/2021 13:03:37.201 WARN  com.kafkatool.common.ExternalDecoderManager - NoClassDefFoundError in tryLoading io.confluent.kafka.formatter.AvroMessageFormatter, ex=kafka/common/MessageFormatter
15/фев/2021 13:03:37.201 WARN  com.kafkatool.common.ExternalDecoderManager - NoClassDefFoundError in tryLoading io.confluent.kafka.serializers.KafkaAvroDecoder, ex=kafka/serializer/Decoder

"These endpoints are stored in a configuration file that you can edit through the menu Tools > Avro plugin settings..."
I have no that point of menu.

And after update content type to Avro and restart client has no effect.

I try in 2.0.7 and 2.0.9 ver

**Comment by laymain** [comment]
That's weird, I have no issue with the 2.0.7 version.
I'll try with the 2.0.9 version

**Comment by laymain** [comment]
I have just tried with a fresh new installation of kafka tool 2.0.9, everything works smoothly.

Can you try with a fresh new install and and mayby redownload the plugin: [kafka-tool-avro-1.0.4-jar-with-dependencies.jar](https://github.com/laymain/kafka-tool-avro/releases/download/1.0.4/kafka-tool-avro-1.0.4-jar-with-dependencies.jar)

**Comment by gex1x** [comment]
I'll try and write.

**Comment by ghost** [comment]
I have faced same issue using Offset Explorer 2.1

**Comment by laymain** [comment]
Ok, i'll give a try using this version

**Comment by ghost** [comment]
any updates according the issue?

**Comment by laymain** [comment]
I can confirm that it works fine with the latest version of Offset Explorer
