### ISSUE TITLE
plugin does not work for kafka tool 2.0.7

### ISSUE THREAD

**Issue by eason0420** [laymain/kafka-tool-avro#6]

**Comment by laymain** [comment]
Thanks for pointing this out. I'll have a look today.

**Comment by laymain** [comment]
I have updated kafka tool to version 2.0.7 and it works smoothly.

Can you provide more information on what's not working?

**Comment by eason0420** [comment]
i use macbook
copy the jar to plugins
damondeMacBook-Pro:PlugIns damonli$ pwd
/Applications/Kafka Tool.app/Contents/PlugIns
damondeMacBook-Pro:PlugIns damonli$ ls -l
total 6152
drwxr-xr-x  3 damonli  admin       96  1 19 15:50 jre.bundle
-rw-r--r--@ 1 damonli  admin  3077094  1 19 15:47 kafka-tool-avro-1.0.4-jar-with-dependencies.jar
damondeMacBook-Pro:PlugIns damonli$

start kafka tool ,but there is no Avro .
![image](https://user-images.githubusercontent.com/40995965/72677276-84e0ee00-3ad5-11ea-98d6-2b8907daf133.png)

**Comment by laymain** [comment]
That's the wrong folder.
I'm not using MacOS but I remember that there is another `plugins` folder (in _lowercase_)
where you should put the _.jar_ file.

Try a `find /Applications/Kafka Tool.app/ -type d -name "plugins"`

**Comment by eason0420** [comment]
i get it,but it do not used for personal user( Feature only available for licensed users).  thank you

**Comment by laymain** [comment]
Yes, unfortunately you have to buy a license to use plugins, even if this plugin is provided free of charge
